server:
  port: 8081

spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 123.57.66.144
    port: 5672
    username: jiang
    password: nidi1995230
    virtual-host: my_vhost
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)

