spring:
  redis:
    password: nidi1995230
    timeout: 100 # 超时时间
    cluster:
      nodes:
        - 81.69.240.49:6379
        - 81.69.240.49:6380
        - 81.69.240.49:6381
    sentinel:
      master: mymaster
      nodes:
        - 81.69.240.49:26379
        - 81.69.240.49:26380
        - 81.69.240.49:26381
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-wait: 1000ms # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-idle: 5 # 连接池中的最大空闲连接 默认为8
        min-idle: 0 # 连接池中的最小空闲连接 默认为 0


